import React,{useState,useRef}from"react";import{createRoot}from"react-dom/client";import{Mic,Download,Undo2,Trash2,Plus,Minus,Maximize2}from"lucide-react";import"./styles.css";
const S=60;const meters=v=>v*1000/S;
function wallName(s){return Math.abs(s.x2-s.x1)>Math.abs(s.y2-s.y1)?s.y1<350?"верхняя":"нижняя":s.x1<500?"левая":"правая"}
function parse(text,state){let t=text.toLowerCase().replaceAll("ё","е").replaceAll(",",".");let n=[...t.matchAll(/(\d+(?:\.\d+)?)/g)].map(x=>+x[1]);let next={...state,segments:[...state.segments],objects:[...state.objects]};if(!n.length)return[next,"Не нашёл размеры."];let last=next.segments.at(-1)||{x1:120,y1:500,x2:120,y2:500};
if(t.includes("высот")){next.height=n[0];return[next,`Высота: H = ${n[0].toFixed(2)} м`]}
if(t.includes("окн")){next.objects.push({type:"window",w:n[0],h:n[1]??2,o:n[2]??0,wall:wallName(last)});return[next,`Окно: W=${n[0].toFixed(2)} м, H=${(n[1]??2).toFixed(2)} м, отступ=${(n[2]??0).toFixed(2)} м`]}
if(t.includes("двер")){next.objects.push({type:"door",w:n[0],h:n[1]??2.1,o:n[2]??0,wall:wallName(last)});return[next,`Дверь: W=${n[0].toFixed(2)} м, H=${(n[1]??2.1).toFixed(2)} м`]}
let d=meters(n[0]),dx=0,dy=0;if(t.includes("прям")||t.includes("вправ"))dx=d;else if(t.includes("налев")||t.includes("влев"))dx=-d;else if(t.includes("вверх"))dy=-d;else if(t.includes("вниз"))dy=d;else dx=d;let seg={x1:last.x2,y1:last.y2,x2:last.x2+dx,y2:last.y2+dy};next.segments.push(seg);return[next,`Стена: ${n[0].toFixed(2)} м ${dx>0?"вправо":dx<0?"влево":dy<0?"вверх":"вниз"}`]}
function App(){let[state,setState]=useState({segments:[],objects:[],height:null}),[listen,setListen]=useState(false),[txt,setTxt]=useState(""),[msg,setMsg]=useState("Готов. Скажите первую стену."),[scale,setScale]=useState(1),rec=useRef();
function voice(){let SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){setMsg("Распознавание речи недоступно. Откройте в Safari и разрешите микрофон.");return}if(listen){rec.current.stop();return}let r=new SR();rec.current=r;r.lang="ru-RU";r.onstart=()=>setListen(true);r.onresult=e=>{let q=e.results[0][0].transcript;setTxt(q);let[a,b]=parse(q,state);setState(a);setMsg(b)};r.onerror=()=>setMsg("Ошибка распознавания.");r.onend=()=>setListen(false);r.start()}
function apply(q){setTxt(q);let[a,b]=parse(q,state);setState(a);setMsg(b)}
function svg(){let x=document.querySelector("#cad").outerHTML,b=new Blob([x],{type:"image/svg+xml"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="voice-cad.svg";a.click()}
return <div className="app"><header><div><b>VOICE CAD</b><small>ГОЛОСОВОЙ ЧЕРТЁЖНИК</small></div><button onClick={svg}><Download size={17}/>SVG</button></header><main><section className="canvasWrap"><div className="info">План помещения {state.height&&<strong>H = {state.height.toFixed(2)} м</strong>}</div><div className="canvas"><svg id="cad" viewBox="0 0 1000 700" style={{transform:`scale(${scale})`}}><defs><pattern id="g" width="25" height="25" patternUnits="userSpaceOnUse"><path d="M25 0H0V25" fill="none" stroke="#e5e7eb"/></pattern></defs><rect width="1000" height="700" fill="white"/><rect width="1000" height="700" fill="url(#g)"/>{state.segments.map((s,i)=><g key={i}><line x1={s.x1} y1={s.y1} x2={s.x2} y2={s.y2} stroke="#111827" strokeWidth="8"/><text x={(s.x1+s.x2)/2} y={(s.y1+s.y2)/2-12} textAnchor="middle" className="dim">{(Math.hypot(s.x2-s.x1,s.y2-s.y1)*S/1000).toFixed(2)} м</text></g>)}{state.objects.map((o,i)=><g key={i}>{o.type==="window"?<rect x={430+i*3} y={495} width={Math.max(45,o.w*35)} height="9" fill="#2563eb"/>:<path d={`M${430+i*3} 500h${Math.max(35,o.w*35)}`} stroke="#dc2626" strokeWidth="9"/>}<text x={440+i*3} y="470" className="obj">{o.type==="window"?"ОКНО":"ДВЕРЬ"} W={o.w.toFixed(2)} H={o.h.toFixed(2)}</text></g>)}{state.height&&<text x="780" y="620" className="height">H = {state.height.toFixed(2)} м</text>}</svg></div><div className="zoom"><button onClick={()=>setScale(Math.max(.6,scale-.1))}><Minus/></button><span>{Math.round(scale*100)}%</span><button onClick={()=>setScale(Math.min(1.5,scale+.1))}><Plus/></button><button onClick={()=>setScale(1)}><Maximize2/></button></div></section><section className="controls"><div className="cmd"><small>ПОСЛЕДНЯЯ КОМАНДА</small><b>{txt||"—"}</b><p>{msg}</p></div><button className={"mic "+(listen?"on":"")} onClick={voice}><Mic/>{listen?"Слушаю…":"Говорить"}</button><div className="examples"><b>Быстрые команды</b>{["5 метров прямо","2 метра налево","Окно ширина 1,5 высота 2 отступ 0,5","Дверь 0,9 на 2,1","Высота 3 метра"].map(q=><button key={q} onClick={()=>apply(q)}>«{q}»</button>)}</div><div className="bottom"><button onClick={()=>setState(s=>({...s,segments:s.segments.slice(0,-1)}))}><Undo2/>Отменить</button><button onClick={()=>{setState({segments:[],objects:[],height:null});setMsg("Чертёж очищен.")}}><Trash2/>Очистить</button></div></section></main></div>}createRoot(document.getElementById("root")).render(<App/>);